create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     email varchar(320) not null unique,
    password_hash varchar(255) not null,
    name varchar(50) not null,
    phone varchar(20),
    status varchar(20) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null
    );

create table if not exists products (
                                        id bigint generated by default as identity primary key,
                                        name varchar(200) not null,
    description text,
    price bigint not null,
    status varchar(20) not null,
    thumbnail_url varchar(500),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null
    );

create table if not exists product_stock (
                                             product_id bigint primary key references products(id),
    quantity int not null,
    updated_at timestamptz not null default now()
    );

create table if not exists carts (
                                     id bigint generated by default as identity primary key,
                                     user_id bigint not null unique references users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists cart_items (
                                          id bigint generated by default as identity primary key,
                                          cart_id bigint not null references carts(id),
    product_id bigint not null references products(id),
    quantity int not null,
    unit_price bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (cart_id, product_id)
    );

create table if not exists orders (
                                      id bigint generated by default as identity primary key,
                                      order_no varchar(30) not null unique,
    user_id bigint not null references users(id),
    status varchar(20) not null,
    total_amount bigint not null,
    receiver_name varchar(50) not null,
    receiver_phone varchar(20) not null,
    zip_code varchar(10) not null,
    address1 varchar(200) not null,
    address2 varchar(200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists order_items (
                                           id bigint generated by default as identity primary key,
                                           order_id bigint not null references orders(id),
    product_id bigint not null references products(id),
    product_name varchar(200) not null,
    unit_price bigint not null,
    quantity int not null,
    line_amount bigint not null
    );

create index if not exists idx_products_status_id on products(status, id);
create index if not exists idx_orders_user_created_at on orders(user_id, created_at desc);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_cart_items_cart_id on cart_items(cart_id);