-- Users & Roles
create table if not exists roles (
                                     id bigint generated by default as identity primary key,
                                     code varchar(30) not null unique
    );

create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     email varchar(320) not null unique,
    password_hash varchar(255) not null,
    name varchar(50) not null,
    phone varchar(20),
    status varchar(20) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
    );

create table if not exists user_roles (
                                          user_id bigint not null references users(id),
    role_id bigint not null references roles(id),
    primary key (user_id, role_id)
    );

create table if not exists user_addresses (
                                              id bigint generated by default as identity primary key,
                                              user_id bigint not null references users(id),
    label varchar(30),
    receiver_name varchar(50) not null,
    receiver_phone varchar(20) not null,
    zip_code varchar(10) not null,
    address1 varchar(200) not null,
    address2 varchar(200),
    is_default boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
    );

-- Categories & Products
create table if not exists categories (
                                          id bigint generated by default as identity primary key,
                                          name varchar(100) not null,
    parent_id bigint references categories(id),
    sort_order int not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
    );

create table if not exists products (
                                        id bigint generated by default as identity primary key,
                                        name varchar(200) not null,
    description text,
    price bigint not null,
    status varchar(20) not null,
    thumbnail_url varchar(500),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
    );

create table if not exists product_categories (
                                                  product_id bigint not null references products(id),
    category_id bigint not null references categories(id),
    primary key (product_id, category_id)
    );

create table if not exists product_images (
                                              id bigint generated by default as identity primary key,
                                              product_id bigint not null references products(id),
    image_url varchar(500) not null,
    sort_order int not null
    );

create table if not exists product_stock (
                                             product_id bigint primary key references products(id),
    quantity int not null,
    updated_at timestamptz not null default now()
    );

-- Carts
create table if not exists carts (
                                     id bigint generated by default as identity primary key,
                                     user_id bigint not null unique references users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
    );

create table if not exists cart_items (
                                          id bigint generated by default as identity primary key,
                                          cart_id bigint not null references carts(id),
    product_id bigint not null references products(id),
    quantity int not null,
    unit_price bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz,
    unique (cart_id, product_id)
    );

-- Orders & Payments
create table if not exists orders (
                                      id bigint generated by default as identity primary key,
                                      order_no varchar(30) not null unique,
    user_id bigint not null references users(id),
    status varchar(20) not null,
    total_amount bigint not null,
    receiver_name varchar(50) not null,
    receiver_phone varchar(20) not null,
    zip_code varchar(10) not null,
    address1 varchar(200) not null,
    address2 varchar(200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

create table if not exists order_items (
                                           id bigint generated by default as identity primary key,
                                           order_id bigint not null references orders(id),
    product_id bigint not null references products(id),
    product_name varchar(200) not null,
    unit_price bigint not null,
    quantity int not null,
    line_amount bigint not null
    );

create table if not exists payments (
                                        id bigint generated by default as identity primary key,
                                        order_id bigint not null unique references orders(id),
    method varchar(20),
    status varchar(20),
    pg_tx_id varchar(100),
    paid_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
    );

-- Indexes
create index if not exists idx_products_status_id on products(status, id);
create index if not exists idx_orders_user_created_at on orders(user_id, created_at desc);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_cart_items_cart_id on cart_items(cart_id);
create index if not exists idx_categories_parent_id on categories(parent_id);